title: "Sharry Blog"
description: "An Android Developer"
url: "https://sharrychoo.github.io/blog"
baseurl: "/blog"
author: "Sharry"
paginate: 5
paginate_path: "/blog/page:num/"

theme: jekyll-theme-mdui

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs